#ifndef GUARD_ACE_GENERIC_SCREEN_H
#define GUARD_ACE_GENERIC_SCREEN_H

#define SCREEN_PAL_WIDTH 320
#define SCREEN_PAL_HEIGHT 256
#define SCREEN_PAL_HIRES_WIDTH 640
#define SCREEN_PAL_LACED_WIDTH 512

#define SCREEN_NTSC_WIDTH 320
#define SCREEN_NTSC_HEIGHT 200
#define SCREEN_NTSC_HIRES_WIDTH 640
#define SCREEN_HTSC_LACED_HEIGHT 400

#endif // GUARD_ACE_GENERIC_SCREEN_H
