set(ACE_LIBRARY_KIND OBJECT CACHE STRING "Build kind: static library or bunch of .o files. OBJECT allows for more link-time optimizations.")
set(ACE_LIBRARY_KINDS "OBJECT" "STATIC")
set_property(CACHE ACE_LIBRARY_KIND PROPERTY STRINGS ${ACE_LIBRARY_KINDS})
set(ACE_DEBUG OFF CACHE BOOL "Build with ACE-specific debug/safety functionality.")
set(ACE_DEBUG_UAE OFF CACHE BOOL "With ACE_DEBUG enabled, output log to UAE console.")
set(ACE_BOB_WRAP_Y ON CACHE BOOL "Conrols Y-wrapping support in bob manager. Disable for extra performance in simple buffer scenarios.")
set(ACE_BOB_PRISTINE_BUFFER OFF CACHE BOOL "When enabled, uses pristine buffer for bob undraw instead of allocating restore buffers.")
set(ACE_USE_ECS_FEATURES OFF CACHE BOOL "Enable ECS feature sets, makes ACE OCS-incompatible.")
set(ACE_TILEBUFFER_TILE_TYPE UBYTE CACHE STRING "Tilebuffer: Specify type used for storing tile indices.")
set(ACE_SCROLLBUFFER_POT_BITMAP_HEIGHT ON CACHE BOOL "Scroll/tilebuffer: Round up the frame buffer height to power of two. More memory usage but faster calculations.")
set(ACE_SCROLLBUFFER_ENABLE_SCROLL_X ON CACHE BOOL "Scroll/tilebuffer: Enables scroll in X direction.")
set(ACE_SCROLLBUFFER_ENABLE_SCROLL_Y ON CACHE BOOL "Scroll/tilebuffer: Enables scroll in Y direction.")
set(ACE_SCROLLBUFFER_X_MARGIN_SIZE 1 CACHE STRING "Scroll/tilebuffer: Number of tiles comprising into offscreen margins in X direction. Bigger allows drawing in bigger objects than tile size.")
set(ACE_SCROLLBUFFER_Y_MARGIN_SIZE 1 CACHE STRING "Scroll/tilebuffer: Number of tiles comprising into offscreen margins in X direction. Bigger allows drawing in bigger objects than tile size.")
set(ACE_FILE_USE_ONLY_DISK OFF CACHE BOOL "If enabled, only diskFile functions will be available for file access.")

message(STATUS "[ACE] ACE_LIBRARY_KIND: '${ACE_LIBRARY_KIND}'")
message(STATUS "[ACE] ACE_DEBUG: '${ACE_DEBUG}'")
message(STATUS "[ACE] ACE_DEBUG_UAE: '${ACE_DEBUG_UAE}'")
message(STATUS "[ACE] ACE_BOB_WRAP_Y: '${ACE_BOB_WRAP_Y}'")
message(STATUS "[ACE] ACE_BOB_PRISTINE_BUFFER: '${ACE_BOB_PRISTINE_BUFFER}'")
message(STATUS "[ACE] ACE_USE_ECS_FEATURES: '${ACE_USE_ECS_FEATURES}'")
message(STATUS "[ACE] ACE_TILEBUFFER_TILE_TYPE: '${ACE_TILEBUFFER_TILE_TYPE}'")
message(STATUS "[ACE] ACE_SCROLLBUFFER_POT_BITMAP_HEIGHT: '${ACE_SCROLLBUFFER_POT_BITMAP_HEIGHT}'")
message(STATUS "[ACE] ACE_SCROLLBUFFER_ENABLE_SCROLL_X: '${ACE_SCROLLBUFFER_ENABLE_SCROLL_X}'")
message(STATUS "[ACE] ACE_SCROLLBUFFER_ENABLE_SCROLL_Y: '${ACE_SCROLLBUFFER_ENABLE_SCROLL_Y}'")
message(STATUS "[ACE] ACE_SCROLLBUFFER_X_MARGIN_SIZE: '${ACE_SCROLLBUFFER_X_MARGIN_SIZE}'")
message(STATUS "[ACE] ACE_SCROLLBUFFER_Y_MARGIN_SIZE: '${ACE_SCROLLBUFFER_Y_MARGIN_SIZE}'")
message(STATUS "[ACE] ACE_FILE_USE_ONLY_DISK: '${ACE_FILE_USE_ONLY_DISK}'")
